# Generated by Django 4.0.3 on 2022-04-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_current_bid_alter_comment_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
