# Generated by Django 4.0.3 on 2022-04-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
