# Generated by Django 4.0.3 on 2022-04-19 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_category_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(choices=[('misc', 'misc'), ('art', 'art'), ('electronics', 'electronics'), ('auto', 'auto'), ('toys', 'toys'), ('books', 'books'), ('clothing', 'clothing')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category'),
        ),
    ]
