# Generated by Django 4.0.3 on 2022-04-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_category_alter_category_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('misc', 'Misc'), ('art', 'Art'), ('electronics', 'Electronics'), ('auto', 'Auto'), ('toys', 'Toys'), ('books', 'Books'), ('clothing', 'Clothing')], default='misc', max_length=11, null=True),
        ),
    ]
