# Generated by Django 4.0.3 on 2022-04-20 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_delete_category_alter_auction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(1, 'Misc'), (2, 'Art'), (3, 'Electronics'), (4, 'Auto'), (5, 'Toys'), (6, 'Books'), (7, 'Clothing')], max_length=11, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category'),
        ),
    ]
