# Generated by Django 4.0.3 on 2022-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.IntegerField(choices=[(1, 'Misc'), (2, 'Art'), (3, 'Electronics'), (4, 'Auto'), (5, 'Toys'), (6, 'Books'), (7, 'Clothing')], null=True),
        ),
    ]
