# Generated by Django 4.0.3 on 2022-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
